spring:
  main:
    allow-circular-references: 'true'
    allow-bean-definition-overriding: 'true'
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USER_NAME}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
    password: ${EMAIL_KEY}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: rootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/preorder
  data:
    redis:
      port: '6379'
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
      max-poll-records: 1000
      fetch-max-wait: 3s
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: '8081'
